from typing import Dict, NamedTuple, Optional

from BaseClasses import Item, ItemClassification


class KronikiElevenaItem(Item):
    game: str = "Kroniki Elevena"


class KronikiElevenaItemData(NamedTuple):
    category: str
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.filler
    max_quantity: int = 1
    weight: int = 1


def get_items_by_category(category: str) -> Dict[str, KronikiElevenaItemData]:
    item_dict: Dict[str, KronikiElevenaItemData] = {}
    for name, data in item_table.items():
        if data.category == category:
            item_dict.setdefault(name, data)

    return item_dict


item_table: Dict[str, KronikiElevenaItemData] = {
    # Characters
    "Cupcake":                   KronikiElevenaItemData("Party",      213700_000, ItemClassification.useful),
    "Plush Foxy":                KronikiElevenaItemData("Party",      213700_001, ItemClassification.useful),
    "Turret":                    KronikiElevenaItemData("Party",      213700_002, ItemClassification.useful),
    "Zombie":                    KronikiElevenaItemData("Party",      213700_003, ItemClassification.useful),
    "Pająk":                     KronikiElevenaItemData("Party",      213700_004, ItemClassification.useful),
    "Chlebek":                   KronikiElevenaItemData("Party",      213700_005, ItemClassification.useful),
    "Galaretka":                 KronikiElevenaItemData("Party",      213700_006, ItemClassification.useful),
    "Hater":                     KronikiElevenaItemData("Party",      213700_007, ItemClassification.useful),
    "Dip":                       KronikiElevenaItemData("Party",      213700_008, ItemClassification.useful),
    "Bob's Brain":               KronikiElevenaItemData("Party",      213700_009, ItemClassification.useful),
    "Bóbr":                      KronikiElevenaItemData("Party",      213700_010, ItemClassification.useful),
    "Mroklum":                   KronikiElevenaItemData("Party",      213700_011, ItemClassification.useful),
    "Robopirat":                 KronikiElevenaItemData("Party",      213700_012, ItemClassification.useful),
    "Worms":                     KronikiElevenaItemData("Party",      213700_013, ItemClassification.useful),
    "Slender":                   KronikiElevenaItemData("Party",      213700_014, ItemClassification.useful),
    "Dingle":                    KronikiElevenaItemData("Party",      213700_015, ItemClassification.useful),
    "Chica":                     KronikiElevenaItemData("Party",      213700_016, ItemClassification.useful),
    "SCP-173":                   KronikiElevenaItemData("Party",      213700_017, ItemClassification.useful),
    "Blue Baby":                 KronikiElevenaItemData("Party",      213700_018, ItemClassification.useful),
    "Alex":                      KronikiElevenaItemData("Party",      213700_019, ItemClassification.useful),
    "Robopirat Ninja":           KronikiElevenaItemData("Party",      213700_020, ItemClassification.useful),
    "Andre":                     KronikiElevenaItemData("Party",      213700_021, ItemClassification.useful),
    "Globox":                    KronikiElevenaItemData("Party",      213700_022, ItemClassification.useful),
    "Android":                   KronikiElevenaItemData("Party",      213700_023, ItemClassification.useful),
    "Specimen 2":                KronikiElevenaItemData("Party",      213700_024, ItemClassification.useful),
    "Baloon Boy":                KronikiElevenaItemData("Party",      213700_025, ItemClassification.useful),
    "Toy Bonnie":                KronikiElevenaItemData("Party",      213700_026, ItemClassification.useful),
    "Rayman":                    KronikiElevenaItemData("Party",      213700_027, ItemClassification.useful),
    "Kao":                       KronikiElevenaItemData("Party",      213700_028, ItemClassification.useful),
    "Boogeyman":                 KronikiElevenaItemData("Party",      213700_029, ItemClassification.useful),
    "Spooky":                    KronikiElevenaItemData("Party",      213700_030, ItemClassification.useful),
    "Freddy":                    KronikiElevenaItemData("Party",      213700_031, ItemClassification.useful),
    "Złoty Freddy":              KronikiElevenaItemData("Party",      213700_032, ItemClassification.useful),
    "Phantom Foxy":              KronikiElevenaItemData("Party",      213700_033, ItemClassification.useful),
    "SCP-049":                   KronikiElevenaItemData("Party",      213700_034, ItemClassification.useful),
    "Reflux":                    KronikiElevenaItemData("Party",      213700_035, ItemClassification.useful),
    "Jeff":                      KronikiElevenaItemData("Party",      213700_036, ItemClassification.useful),
    "Isaac":                     KronikiElevenaItemData("Party",      213700_037, ItemClassification.useful),
    "Azazel":                    KronikiElevenaItemData("Party",      213700_038, ItemClassification.useful),
    "Monstro II":                KronikiElevenaItemData("Party",      213700_039, ItemClassification.useful),
    "Brzytwobrody":              KronikiElevenaItemData("Party",      213700_040, ItemClassification.useful),
    "Fuckboy":                   KronikiElevenaItemData("Party",      213700_041, ItemClassification.useful),
    "Purple Guy":                KronikiElevenaItemData("Party",      213700_042, ItemClassification.useful),
    "BB":                        KronikiElevenaItemData("Party",      213700_043, ItemClassification.useful),
    "SCP-106":                   KronikiElevenaItemData("Party",      213700_044, ItemClassification.useful),
    "Kukiełka":                  KronikiElevenaItemData("Party",      213700_045, ItemClassification.useful),
    "Ultra Greed":               KronikiElevenaItemData("Party",      213700_046, ItemClassification.useful),
    "Anim":                      KronikiElevenaItemData("Party",      213700_047, ItemClassification.useful),
    "Cat Mario":                 KronikiElevenaItemData("Party",      213700_048, ItemClassification.useful),
    "Indiana":                   KronikiElevenaItemData("Party",      213700_049, ItemClassification.useful),
    "Serek(Kapłan)":             KronikiElevenaItemData("Party",      213700_050, ItemClassification.progression),
    "Lara Croft":                KronikiElevenaItemData("Party",      213700_051, ItemClassification.useful),
    "Serek(Wsparcie)":           KronikiElevenaItemData("Party",      213700_052, ItemClassification.useful),
    "Kaktus mag":                KronikiElevenaItemData("Party",      213700_053, ItemClassification.useful),
    "Papyrus":                   KronikiElevenaItemData("Party",      213700_054, ItemClassification.progression),
    
    # Key Items
    "Kontroler":                 KronikiElevenaItemData("Quest",         213700_055, ItemClassification.progression_skip_balancing),
    "Krótkofalówka":             KronikiElevenaItemData("Quest",         213700_056, ItemClassification.progression_skip_balancing),
    "Siekiera":                  KronikiElevenaItemData("Quest",         213700_057, ItemClassification.progression),
    "Młotek":                    KronikiElevenaItemData("Quest",         213700_058, ItemClassification.progression),
    "Karta klucz I":             KronikiElevenaItemData("Quest",         213700_059, ItemClassification.progression),
    "Karta klucz II":            KronikiElevenaItemData("Quest",         213700_060, ItemClassification.progression),
    "Karta klucz V":             KronikiElevenaItemData("Quest",         213700_061, ItemClassification.progression),
    "Przenośny teleport":        KronikiElevenaItemData("Quest",         213700_062, ItemClassification.progression),
    "Kartka papieru":            KronikiElevenaItemData("Quest",         213700_063, ItemClassification.progression),
    "Tajemnicza część":          KronikiElevenaItemData("Quest",         213700_064, ItemClassification.progression,           4),
    "Buty Laury":                KronikiElevenaItemData("Quest",         213700_065, ItemClassification.progression),
    "Dysk do rzucania":          KronikiElevenaItemData("Quest",         213700_066, ItemClassification.progression),
    "Złoty klucz":               KronikiElevenaItemData("Quest",         213700_067, ItemClassification.progression),
    "Guziczek":                  KronikiElevenaItemData("Quest",         213700_068, ItemClassification.progression),
    "Ołówek i gumka":            KronikiElevenaItemData("Quest",         213700_069, ItemClassification.progression),
    "Antygrawitacyjne buty":     KronikiElevenaItemData("Quest",         213700_070, ItemClassification.progression),
    "Klucz":                     KronikiElevenaItemData("Quest",         213700_071, ItemClassification.progression),
    
    # Quest Items
    "Złoty grzyb":               KronikiElevenaItemData("Quest",         213700_072, ItemClassification.progression,           5),
    "Sos grzybowy":              KronikiElevenaItemData("Quest",         213700_073, ItemClassification.useful),
    
    # Fillers
    "Jabłko":                    KronikiElevenaItemData("Filler",        213700_074, weight=4, max_quantity=15),
    "Winogrono":                 KronikiElevenaItemData("Filler",        213700_075, weight=4, max_quantity=15),
    "Mandarynka":                KronikiElevenaItemData("Filler",        213700_076, weight=2, max_quantity=15),
    "Wiśnie":                    KronikiElevenaItemData("Filler",        213700_077, weight=3, max_quantity=15),
    "Zioła":                     KronikiElevenaItemData("Filler",        213700_078, weight=1, max_quantity=15),
    "Czerwony lum":              KronikiElevenaItemData("Filler",        213700_079, weight=1, max_quantity=10),
    "Niebieski lum":             KronikiElevenaItemData("Filler",        213700_080, weight=1, max_quantity=10),
    "Żółty lum":                 KronikiElevenaItemData("Filler",        213700_081, weight=1, max_quantity=10),
    "Marchewka":                 KronikiElevenaItemData("Filler",        213700_082, weight=2, max_quantity=15),
    "Srebrny klucz":             KronikiElevenaItemData("Filler",        213700_083, weight=2, max_quantity=10), # i will change it later
    "Pomidor":                   KronikiElevenaItemData("Filler",        213700_084, weight=3, max_quantity=15), 
    "Koniczyna":                 KronikiElevenaItemData("Filler",        213700_085, weight=2, max_quantity=15),
    "Pikantna papryka":          KronikiElevenaItemData("Filler",        213700_086, weight=2, max_quantity=15),
    "Cytryna":                   KronikiElevenaItemData("Filler",        213700_087, weight=1, max_quantity=15),
    "Wyciąg z kaktusa":          KronikiElevenaItemData("Filler",        213700_088, weight=1, max_quantity=15),
    "Penizol":                   KronikiElevenaItemData("Filler",        213700_089, weight=1, max_quantity=5),
    "Prezent":                   KronikiElevenaItemData("Filler",        213700_090, weight=1, max_quantity=10),
    "Mała ognista bomba":        KronikiElevenaItemData("Filler",        213700_091, weight=2, max_quantity=10),
    "Duża ognista bomba":        KronikiElevenaItemData("Filler",        213700_092, weight=2, max_quantity=10),
    "Mała wodna bomba":          KronikiElevenaItemData("Filler",        213700_093, weight=2, max_quantity=10),
    "Duża wodna bomba":          KronikiElevenaItemData("Filler",        213700_094, weight=2, max_quantity=10),
    "Mała ziemna bomba":         KronikiElevenaItemData("Filler",        213700_095, weight=2, max_quantity=10),
    "Duża ziemna bomba":         KronikiElevenaItemData("Filler",        213700_096, weight=2, max_quantity=10),
    "Smocza miłość":             KronikiElevenaItemData("Filler",        213700_097, weight=1, max_quantity=10),
    "Meteoryt ataku":            KronikiElevenaItemData("Filler",        213700_098, weight=2, max_quantity=10),
    "Meteoryt magii":            KronikiElevenaItemData("Filler",        213700_099, weight=2, max_quantity=10),
    "Meteoryt szybkości":        KronikiElevenaItemData("Filler",        213700_100, weight=2, max_quantity=10),
    "Mikstura zdrowia":          KronikiElevenaItemData("Filler",        213700_101, weight=1, max_quantity=10),
    "Mikstura energii":          KronikiElevenaItemData("Filler",        213700_102, weight=1, max_quantity=10),
    "Płynny szał":               KronikiElevenaItemData("Filler",        213700_103, weight=1, max_quantity=10),
    "Gwiezdne Chrupki":          KronikiElevenaItemData("Filler",        213700_104, weight=2, max_quantity=15),
    "Psia kupa":                 KronikiElevenaItemData("Filler",        213700_105, weight=3, max_quantity=10),
    "Kokarda Tarkopsa":          KronikiElevenaItemData("Filler",        213700_106, weight=1, max_quantity=15),
    "Płatek róży":               KronikiElevenaItemData("Filler",        213700_107, weight=1, max_quantity=5),
    "Płatek Tem":                KronikiElevenaItemData("Filler",        213700_108, weight=2, max_quantity=5),
    "Płatek Tem (wyprzedaż)":    KronikiElevenaItemData("Filler",        213700_109, weight=4, max_quantity=5),
    "Płatek Tem (zatruty)":      KronikiElevenaItemData("Filler",        213700_110, weight=3, max_quantity=5),
    "Klejnot many":              KronikiElevenaItemData("Filler",        213700_111, weight=1, max_quantity=10),
    "Klejnot cyberpunktów":      KronikiElevenaItemData("Filler",        213700_112, weight=1, max_quantity=10),
    "Klejnot obrażeń":           KronikiElevenaItemData("Filler",        213700_113, weight=1, max_quantity=10),
    "Klejnot życia":             KronikiElevenaItemData("Filler",        213700_114, weight=1, max_quantity=10),
    "Klejnot ruchu":             KronikiElevenaItemData("Filler",        213700_115, weight=1, max_quantity=10),
    "Olbrzymia ognista bomba":   KronikiElevenaItemData("Filler",        213700_116, weight=1, max_quantity=10),
    "Gwiezdne Chrupki XL":       KronikiElevenaItemData("Filler",        213700_117, weight=1, max_quantity=10),
    "Spaghetti":                 KronikiElevenaItemData("Filler",        213700_118, weight=3, max_quantity=10),
    "Klejnot żywiołów":          KronikiElevenaItemData("Filler",        213700_119, weight=1, max_quantity=5),
    "Babeczka":                  KronikiElevenaItemData("Filler",        213700_120, weight=2, max_quantity=5),
    
    # Key Items 2
    "Jad Venesosa Planta":       KronikiElevenaItemData("Quest",        213700_121, ItemClassification.progression,       1), # I will leater change number if nessesary
    
    # Key Items(Dwienków)
    "Świeczka":                  KronikiElevenaItemData("Quest",        213700_122, ItemClassification.progression),
    "Info. o skrzyni":           KronikiElevenaItemData("Quest",        213700_123, ItemClassification.progression),
    "Info. o książkach":         KronikiElevenaItemData("Quest",        213700_124, ItemClassification.progression),
    "Info. o kominku":           KronikiElevenaItemData("Quest",        213700_125, ItemClassification.progression),
    "Materiał":                  KronikiElevenaItemData("Quest",        213700_126, ItemClassification.progression),
    "Odcisk stopy":              KronikiElevenaItemData("Quest",        213700_127, ItemClassification.progression),
    "Info. o diamencie":         KronikiElevenaItemData("Quest",        213700_128, ItemClassification.progression),
    
    # Key Items(Snowdin)
    "Zeznania Blooka":           KronikiElevenaItemData("Quest",        213700_129, ItemClassification.progression),
    "Zeznania Snowdrake'a":      KronikiElevenaItemData("Quest",        213700_130, ItemClassification.progression),
    "Zielony materiał":          KronikiElevenaItemData("Quest",        213700_131, ItemClassification.progression),
    "Lodowy kolec":              KronikiElevenaItemData("Quest",        213700_132, ItemClassification.progression),
    "Miejsce zbrodni":           KronikiElevenaItemData("Quest",        213700_133, ItemClassification.progression),
    
    # Kapsuły
    "Kapsuła Plush Foxy'ego":    KronikiElevenaItemData("Quest",        213700_134, ItemClassification.useful),
    "Kapsuła Hatera":            KronikiElevenaItemData("Quest",        213700_135, ItemClassification.useful),
    "Kapsuła Dingle'a":          KronikiElevenaItemData("Quest",        213700_136, ItemClassification.useful),
    "Kapsuła Alex'a":            KronikiElevenaItemData("Quest",        213700_137, ItemClassification.useful),
    "Kapsuła Złotego Freddy'ego":KronikiElevenaItemData("Quest",        213700_138, ItemClassification.useful),
    "Kapsuła Kangurka Kao":      KronikiElevenaItemData("Quest",        213700_139, ItemClassification.useful),
    "Kapsuła Fuckboy'a":         KronikiElevenaItemData("Quest",        213700_140, ItemClassification.useful),
    "Kapsuła Anima":             KronikiElevenaItemData("Quest",        213700_141, ItemClassification.useful),
    "Kapsuła Turreta":           KronikiElevenaItemData("Quest",        213700_142, ItemClassification.useful),
    "Kapsuła Mrokluma":          KronikiElevenaItemData("Quest",        213700_143, ItemClassification.useful),
    "Kapsuła Andre":             KronikiElevenaItemData("Quest",        213700_144, ItemClassification.useful),
    "Kapsuła Specimena 2":       KronikiElevenaItemData("Quest",        213700_145, ItemClassification.useful),
    "Kapsuła Foxy'ego":          KronikiElevenaItemData("Quest",        213700_146, ItemClassification.useful),
    "Kapsuła Jeffa":             KronikiElevenaItemData("Quest",        213700_147, ItemClassification.useful),
    "Kapsuła Kukiełki":          KronikiElevenaItemData("Quest",        213700_148, ItemClassification.useful),
    "Kapsuła Ultra Greeda":      KronikiElevenaItemData("Quest",        213700_149, ItemClassification.useful),
    
    # Key Items 3
    "Doggo":                     KronikiElevenaItemData("Quest",        213700_150, ItemClassification.progression),
    "Różowe majciochy":          KronikiElevenaItemData("Quest",        213700_151, ItemClassification.progression),
    "Dusza":                     KronikiElevenaItemData("Quest",        213700_152, ItemClassification.progression),
    "Diament":                   KronikiElevenaItemData("Quest",        213700_153, ItemClassification.progression_skip_balancing,           5),
    
    # Armors
    "Niszczyciel":               KronikiElevenaItemData("Armor",        213700_154, ItemClassification.useful, 4),
    "Deska":                     KronikiElevenaItemData("Armor",        213700_155, ItemClassification.useful, 4),
    "Wzmacniacz zdrowia":        KronikiElevenaItemData("Armor",        213700_156, ItemClassification.useful, 4),
    "Ubijaczka":                 KronikiElevenaItemData("Armor",        213700_157, ItemClassification.useful, 4),
    "Kołdra":                    KronikiElevenaItemData("Armor",        213700_158, ItemClassification.useful, 4),
    "Wspomagacz":                KronikiElevenaItemData("Armor",        213700_159, ItemClassification.useful, 4),
    
    "Kask":                      KronikiElevenaItemData("Armor",        213700_160, ItemClassification.useful, 2),
    "Drewniana tarcza":          KronikiElevenaItemData("Armor",        213700_161, ItemClassification.useful, 2),
    "Kapelusz":                  KronikiElevenaItemData("Armor",        213700_162, ItemClassification.useful, 2),
    "Rubinowy naszyjnik":        KronikiElevenaItemData("Armor",        213700_163, ItemClassification.useful, 2),
    "Pelerynka":                 KronikiElevenaItemData("Armor",        213700_164, ItemClassification.useful, 2),
    "Kapelusz wiedźmy":          KronikiElevenaItemData("Armor",        213700_165, ItemClassification.useful, 2),
    
    "Wilcze szpony":             KronikiElevenaItemData("Armor",        213700_166, ItemClassification.useful, 4),
    "Wilcze futro":              KronikiElevenaItemData("Armor",        213700_167, ItemClassification.useful, 4),
    "Szczurzy ogon":             KronikiElevenaItemData("Armor",        213700_168, ItemClassification.useful, 4),
    "Złote pięści":              KronikiElevenaItemData("Armor",        213700_169, ItemClassification.useful, 4),
    "Różaniec":                  KronikiElevenaItemData("Armor",        213700_170, ItemClassification.useful, 4),
    "Karta Mądrości":            KronikiElevenaItemData("Armor",        213700_171, ItemClassification.useful, 4),
    "Lewy but":                  KronikiElevenaItemData("Armor",        213700_172, ItemClassification.useful, 4),
    "Czarna dziura":             KronikiElevenaItemData("Armor",        213700_173, ItemClassification.useful, 4),
    "Pistolet":                  KronikiElevenaItemData("Armor",        213700_174, ItemClassification.useful, 4),
    "Błyskawica":                KronikiElevenaItemData("Armor",        213700_175, ItemClassification.useful, 4),
    "Głaz":                      KronikiElevenaItemData("Armor",        213700_176, ItemClassification.useful, 4),
    "Kupa gruzu":                KronikiElevenaItemData("Armor",        213700_177, ItemClassification.useful, 4),
    "Toksyczna zbroja":          KronikiElevenaItemData("Armor",        213700_178, ItemClassification.useful, 4),
    "Dopalacz":                  KronikiElevenaItemData("Armor",        213700_179, ItemClassification.useful, 4),
    "Kapelusz złodzieja":        KronikiElevenaItemData("Armor",        213700_180, ItemClassification.useful, 4),
    "Odnawiacz zdrowia I":       KronikiElevenaItemData("Armor",        213700_181, ItemClassification.useful, 4),

    "Kamienna tarcza":           KronikiElevenaItemData("Armor",        213700_182, ItemClassification.useful, 2),
    "Drewniany puklerz":         KronikiElevenaItemData("Armor",        213700_183, ItemClassification.useful, 2),
    "Kamienny puklerz":          KronikiElevenaItemData("Armor",        213700_184, ItemClassification.useful, 2),
    "Peleryna":                  KronikiElevenaItemData("Armor",        213700_185, ItemClassification.useful, 2),
    "Szata ciemności":           KronikiElevenaItemData("Armor",        213700_186, ItemClassification.useful, 2),
    "Szaty księcia":             KronikiElevenaItemData("Armor",        213700_187, ItemClassification.useful, 2),
    "Żelazne rękawice":          KronikiElevenaItemData("Armor",        213700_188, ItemClassification.useful, 2),
    "Mistyczny kapelusz":        KronikiElevenaItemData("Armor",        213700_189, ItemClassification.useful, 2),
    "Hełm rycerza":              KronikiElevenaItemData("Armor",        213700_190, ItemClassification.useful, 2),
    "Królicze uszy":             KronikiElevenaItemData("Armor",        213700_191, ItemClassification.useful, 2),

    "Srebrny miecz":             KronikiElevenaItemData("Armor",         213700_192, ItemClassification.useful, 4),
    "Obieraczka":                KronikiElevenaItemData("Armor",         213700_193, ItemClassification.useful, 4),
    "Mistyczne ostrze":          KronikiElevenaItemData("Armor",         213700_194, ItemClassification.useful, 4),
    "Złoty łuk":                 KronikiElevenaItemData("Armor",         213700_195, ItemClassification.useful, 4),
    "Różdżka":                   KronikiElevenaItemData("Armor",         213700_196, ItemClassification.useful, 4),
    "Patyk":                     KronikiElevenaItemData("Armor",         213700_197, ItemClassification.useful, 4),
    "Zachód słońca":             KronikiElevenaItemData("Armor",         213700_198, ItemClassification.useful, 4),
    "Gówniana tarcza":           KronikiElevenaItemData("Armor",         213700_199, ItemClassification.useful, 4),
    "Kartka papieru":            KronikiElevenaItemData("Armor",         213700_200, ItemClassification.useful, 4),
    "Narysowany pancerz":        KronikiElevenaItemData("Armor",         213700_201, ItemClassification.useful, 4),
    "Gówniany zapach":           KronikiElevenaItemData("Armor",         213700_202, ItemClassification.useful, 4),
    "Technologia":               KronikiElevenaItemData("Armor",         213700_203, ItemClassification.useful, 4),
    "Złote pióro":               KronikiElevenaItemData("Armor",         213700_204, ItemClassification.useful, 4),
    "Zajebisty but":             KronikiElevenaItemData("Armor",         213700_205, ItemClassification.useful, 4),
    "Armor mocy":                KronikiElevenaItemData("Armor",         213700_206, ItemClassification.useful, 4),
    "Karta Skilla I":            KronikiElevenaItemData("Armor",         213700_207, ItemClassification.useful, 4),

    "Opaska bohatera":           KronikiElevenaItemData("Armor",         213700_208, ItemClassification.useful, 2),
    "Smoczy amulet":             KronikiElevenaItemData("Armor",         213700_209, ItemClassification.useful, 2),
    "Cegła":                     KronikiElevenaItemData("Armor",         213700_210, ItemClassification.useful, 2),
    "Magiczna tarcza":           KronikiElevenaItemData("Armor",         213700_211, ItemClassification.useful, 2),

    "Jopek":                     KronikiElevenaItemData("Armor",         213700_212, ItemClassification.useful, 4),
    "Damka":                     KronikiElevenaItemData("Armor",         213700_213, ItemClassification.useful, 4),
    "Król":                      KronikiElevenaItemData("Armor",         213700_214, ItemClassification.useful, 4),
    "As":                        KronikiElevenaItemData("Armor",         213700_215, ItemClassification.useful, 4),
    "Dzida":                     KronikiElevenaItemData("Armor",         213700_216, ItemClassification.useful, 4),
    "Srebrna Dzida":             KronikiElevenaItemData("Armor",         213700_217, ItemClassification.useful, 4),
    "Złota Dzida":               KronikiElevenaItemData("Armor",         213700_218, ItemClassification.useful, 4),
    "Diamentowa Dzida":          KronikiElevenaItemData("Armor",         213700_219, ItemClassification.useful, 4),
    "Kubek Zdrowia":             KronikiElevenaItemData("Armor",         213700_220, ItemClassification.useful, 4),
    "Worek Zdrowia":             KronikiElevenaItemData("Armor",         213700_221, ItemClassification.useful, 4),
    "Wiadro Zdrowia":            KronikiElevenaItemData("Armor",         213700_222, ItemClassification.useful, 4),
    "Beczka zdrowia":            KronikiElevenaItemData("Armor",         213700_223, ItemClassification.useful, 4),
    "Skóra Knaarena":            KronikiElevenaItemData("Armor",         213700_224, ItemClassification.useful, 4),

    "Mityczna Bransoleta":       KronikiElevenaItemData("Armor",        213700_225, ItemClassification.useful, 2),
    "Pokrywka":                  KronikiElevenaItemData("Armor",        213700_226, ItemClassification.useful, 2),
    "Kawał metalu":              KronikiElevenaItemData("Armor",        213700_227, ItemClassification.useful, 2),
    "Skórzana czapa":            KronikiElevenaItemData("Armor",        213700_228, ItemClassification.useful, 2),
    "Czapka z daszkiem":         KronikiElevenaItemData("Armor",        213700_229, ItemClassification.useful, 2),
    "Plaster":                   KronikiElevenaItemData("Armor",        213700_230, ItemClassification.useful, 2),
    "Opaska na oko":             KronikiElevenaItemData("Armor",        213700_231, ItemClassification.useful, 2),
    "Bocianie pióro":            KronikiElevenaItemData("Armor",        213700_232, ItemClassification.useful, 2),
    "Czapa mroku":               KronikiElevenaItemData("Armor",        213700_233, ItemClassification.useful, 2),
    "Naddźwiękowe buty":         KronikiElevenaItemData("Armor",        213700_234, ItemClassification.useful, 2),
    "Czterolistna koniczyna":    KronikiElevenaItemData("Armor",        213700_235, ItemClassification.useful, 2),
    "Teletarcza":                KronikiElevenaItemData("Armor",        213700_236, ItemClassification.useful, 2),
    "Aureola":                   KronikiElevenaItemData("Armor",        213700_237, ItemClassification.useful, 2),
    "Amulet lodu":               KronikiElevenaItemData("Armor",        213700_238, ItemClassification.useful, 2),
    "Amulet ognia":              KronikiElevenaItemData("Armor",        213700_239, ItemClassification.useful, 2),
    "Amulet grzmotów":           KronikiElevenaItemData("Armor",        213700_240, ItemClassification.useful, 2),
    "Srebrna tarcza":            KronikiElevenaItemData("Armor",        213700_241, ItemClassification.useful, 2),
    "Pozłacana tarcza":          KronikiElevenaItemData("Armor",        213700_242, ItemClassification.useful, 2),
    "Zbroja rycerza":            KronikiElevenaItemData("Armor",        213700_243, ItemClassification.useful, 2),
    "Płynne szczęście":          KronikiElevenaItemData("Armor",        213700_244, ItemClassification.useful, 2),

    "Petarda":                   KronikiElevenaItemData("Armor",         213700_245, ItemClassification.useful, 4),
    "Dynamit":                   KronikiElevenaItemData("Armor",         213700_246, ItemClassification.useful, 4),
    "Bomba":                     KronikiElevenaItemData("Armor",         213700_247, ItemClassification.useful, 4),
    "Atomówka":                  KronikiElevenaItemData("Armor",         213700_248, ItemClassification.useful, 4),
    "Patyczek":                  KronikiElevenaItemData("Armor",         213700_249, ItemClassification.useful, 4),
    "Laska":                     KronikiElevenaItemData("Armor",         213700_250, ItemClassification.useful, 4),
    "Złota laska":               KronikiElevenaItemData("Armor",         213700_251, ItemClassification.useful, 4),
    "Mistyczna różdżka":         KronikiElevenaItemData("Armor",         213700_252, ItemClassification.useful, 4),
    "Mieszaniec I":              KronikiElevenaItemData("Armor",         213700_253, ItemClassification.useful, 4),
    "Koszulka":                  KronikiElevenaItemData("Armor",         213700_254, ItemClassification.useful, 4),
    "Koszula":                   KronikiElevenaItemData("Armor",         213700_255, ItemClassification.useful, 4),
    "Kurtka":                    KronikiElevenaItemData("Armor",         213700_256, ItemClassification.useful, 4),
    "Kombinezon":                KronikiElevenaItemData("Armor",         213700_257, ItemClassification.useful, 4),
    "Karta Skilla II":           KronikiElevenaItemData("Armor",         213700_258, ItemClassification.useful, 4),
    "Karta Skilla III":          KronikiElevenaItemData("Armor",         213700_259, ItemClassification.useful, 4),
    "Karta Skilla IV":           KronikiElevenaItemData("Armor",         213700_260, ItemClassification.useful, 4),
    "Wspomaganie kierownicy":    KronikiElevenaItemData("Armor",         213700_261, ItemClassification.useful, 4),
    "Okulary przeciwsłoneczne":  KronikiElevenaItemData("Armor",         213700_262, ItemClassification.useful, 4),
    "Respirator":                KronikiElevenaItemData("Armor",         213700_263, ItemClassification.useful, 4),

    "Kocie uszy":                KronikiElevenaItemData("Armor",        213700_264, ItemClassification.useful, 2),
    "Czerwona suknia":           KronikiElevenaItemData("Armor",        213700_265, ItemClassification.useful, 2),
    "Płaszcz Gary'ego":          KronikiElevenaItemData("Armor",        213700_266, ItemClassification.useful, 2),
    "Smoczy hełm":               KronikiElevenaItemData("Armor",        213700_267, ItemClassification.useful, 2),
    "Smocza zbroja":             KronikiElevenaItemData("Armor",        213700_268, ItemClassification.useful, 2),
    "Szaty najwyższego maga":    KronikiElevenaItemData("Armor",        213700_269, ItemClassification.useful, 2),
    "Kamizelka kuloodporna":     KronikiElevenaItemData("Armor",        213700_270, ItemClassification.useful, 2),
    "Złota wstążka":             KronikiElevenaItemData("Armor",        213700_271, ItemClassification.useful, 2),
    "Maska karnawałowa":         KronikiElevenaItemData("Armor",        213700_272, ItemClassification.useful, 2),
    "Tarcza policyjna":          KronikiElevenaItemData("Armor",        213700_273, ItemClassification.useful, 2),

    "Brązowa wstążka":           KronikiElevenaItemData("Armor",         213700_274, ItemClassification.useful, 4),
    "Srebrna wstążka":           KronikiElevenaItemData("Armor",         213700_275, ItemClassification.useful, 4),
    "Złota wstążka":             KronikiElevenaItemData("Armor",         213700_276, ItemClassification.useful, 4),
    "Legendarna wstążka":        KronikiElevenaItemData("Armor",         213700_277, ItemClassification.useful, 4),
    "Brązowa tarcza":            KronikiElevenaItemData("Armor",         213700_278, ItemClassification.useful, 4),
    "Srebrna tarcza":            KronikiElevenaItemData("Armor",         213700_279, ItemClassification.useful, 4),
    "Złota tarcza":              KronikiElevenaItemData("Armor",         213700_280, ItemClassification.useful, 4),
    "Legendarna tarcza":         KronikiElevenaItemData("Armor",         213700_281, ItemClassification.useful, 4),
    "zBrOjA v 0.1":              KronikiElevenaItemData("Armor",         213700_282, ItemClassification.useful, 4),
    "zBrOjA v 0.2":              KronikiElevenaItemData("Armor",         213700_283, ItemClassification.useful, 4),
    "zBrOjA v 0.3":              KronikiElevenaItemData("Armor",         213700_284, ItemClassification.useful, 4),
    "zBrOjA v 0.4":              KronikiElevenaItemData("Armor",         213700_285, ItemClassification.useful, 4),
    "Miseczka":                  KronikiElevenaItemData("Armor",         213700_286, ItemClassification.useful, 4),
    "Miska":                     KronikiElevenaItemData("Armor",         213700_287, ItemClassification.useful, 4),
    "Micha":                     KronikiElevenaItemData("Armor",         213700_288, ItemClassification.useful, 4),
    "Wanna":                     KronikiElevenaItemData("Armor",         213700_289, ItemClassification.useful, 4),
    "Dyskietka":                 KronikiElevenaItemData("Armor",         213700_290, ItemClassification.useful, 4),
    "Płyta":                     KronikiElevenaItemData("Armor",         213700_291, ItemClassification.useful, 4),
    "Dysk":                      KronikiElevenaItemData("Armor",         213700_292, ItemClassification.useful, 4),
    "Chmura":                    KronikiElevenaItemData("Armor",         213700_293, ItemClassification.useful, 4),
    "Stojak":                    KronikiElevenaItemData("Armor",         213700_294, ItemClassification.useful, 4),
    "Statyw":                    KronikiElevenaItemData("Armor",         213700_295, ItemClassification.useful, 4),
    "Mikrofon":                  KronikiElevenaItemData("Armor",         213700_296, ItemClassification.useful, 4),
    "Megafon":                   KronikiElevenaItemData("Armor",         213700_297, ItemClassification.useful, 4),
    "Karta Skilla V":            KronikiElevenaItemData("Armor",         213700_298, ItemClassification.useful, 4),
    "Pierścień śmierci":         KronikiElevenaItemData("Armor",         213700_299, ItemClassification.useful, 4),

    "Brelok żywiołu ognia":      KronikiElevenaItemData("Armor",        213700_300, ItemClassification.useful, 2),
    "Brelok żywiołu lodu":       KronikiElevenaItemData("Armor",        213700_301, ItemClassification.useful, 2),
    "Brelok żywiołu błyskawicy": KronikiElevenaItemData("Armor",        213700_302, ItemClassification.useful, 2),
    "Głowa Bendy'ego":           KronikiElevenaItemData("Armor",        213700_303, ItemClassification.useful, 2),
    "Armor do bicia kobiet":     KronikiElevenaItemData("Armor",        213700_304, ItemClassification.useful, 4),
    "Brelok z Gacusiem":         KronikiElevenaItemData("Armor",        213700_305, ItemClassification.useful, 2),

    # Tem armor
    "Tem armor":                 KronikiElevenaItemData("Armor",        213700_306, ItemClassification.useful, 2),

    # Weapons
    "Zardzewiały miecz":         KronikiElevenaItemData("Weapon",        213700_307, ItemClassification.useful, 2),
    "Tępy nożyk":                KronikiElevenaItemData("Weapon",        213700_308, ItemClassification.useful, 2),
    "Drewniana różdżka":         KronikiElevenaItemData("Weapon",        213700_309, ItemClassification.useful, 2),
    "Używane rękawice":          KronikiElevenaItemData("Weapon",        213700_310, ItemClassification.useful, 2),
    "Ostry nożyk":               KronikiElevenaItemData("Weapon",        213700_311, ItemClassification.useful, 2),
    "Używany miecz":             KronikiElevenaItemData("Weapon",        213700_312, ItemClassification.useful, 2),
    "Kradziona różdżka":         KronikiElevenaItemData("Weapon",        213700_313, ItemClassification.useful, 2),
    "Rękawice":                  KronikiElevenaItemData("Weapon",        213700_314, ItemClassification.useful, 2),
    "Lodołamacz":                KronikiElevenaItemData("Weapon",        213700_315, ItemClassification.useful, 2),
    "Lekki nóż":                 KronikiElevenaItemData("Weapon",        213700_316, ItemClassification.useful, 2),
    "Rękawiczki":                KronikiElevenaItemData("Weapon",        213700_317, ItemClassification.useful, 2),
    "Patyk do hipnozy":          KronikiElevenaItemData("Weapon",        213700_318, ItemClassification.useful, 2),
    "Maczuga":                   KronikiElevenaItemData("Weapon",        213700_319, ItemClassification.useful, 2),
    "Pochodnia":                 KronikiElevenaItemData("Weapon",        213700_320, ItemClassification.useful, 2),
    "Ostrze ciemności":          KronikiElevenaItemData("Weapon",        213700_321, ItemClassification.useful, 2),
    "Zatrute ostrze":            KronikiElevenaItemData("Weapon",        213700_322, ItemClassification.useful, 2),
    "Wodna różdżka":             KronikiElevenaItemData("Weapon",        213700_323, ItemClassification.useful, 2),
    "Laska mocy":                KronikiElevenaItemData("Weapon",        213700_324, ItemClassification.useful, 2),
    "Magiczne rękawice":         KronikiElevenaItemData("Weapon",        213700_325, ItemClassification.useful, 2),
    "Antyczne rękawiczki":       KronikiElevenaItemData("Weapon",        213700_326, ItemClassification.useful, 2),
    "Halabarda":                 KronikiElevenaItemData("Weapon",        213700_327, ItemClassification.useful, 2),
    "Trujący miecz":             KronikiElevenaItemData("Weapon",        213700_328, ItemClassification.useful, 2),
    "Zestaw Rycerza":            KronikiElevenaItemData("Weapon",        213700_329, ItemClassification.useful, 2),
    "Srebrny miecz":             KronikiElevenaItemData("Weapon",        213700_330, ItemClassification.useful, 2),
    "Różdżka grzmotu":           KronikiElevenaItemData("Weapon",        213700_331, ItemClassification.useful, 2),
    "Kij Wielkiego Maga":        KronikiElevenaItemData("Weapon",        213700_332, ItemClassification.useful, 2),
    "PARALIZATOR":               KronikiElevenaItemData("Weapon",        213700_333, ItemClassification.useful, 2),
    "Wyważona laska":            KronikiElevenaItemData("Weapon",        213700_334, ItemClassification.useful, 2),
    "Skórzane rękawice":         KronikiElevenaItemData("Weapon",        213700_335, ItemClassification.useful, 2),
    "Dziurawe Rękawiczki":       KronikiElevenaItemData("Weapon",        213700_336, ItemClassification.useful, 2),
    "Kastet":                    KronikiElevenaItemData("Weapon",        213700_337, ItemClassification.useful, 2),
    "Pozłacane Rękawice":        KronikiElevenaItemData("Weapon",        213700_338, ItemClassification.useful, 2),
    "Srebrny nóż":               KronikiElevenaItemData("Weapon",        213700_339, ItemClassification.useful, 2),
    "Wodny nożyk":               KronikiElevenaItemData("Weapon",        213700_340, ItemClassification.useful, 2),
    "Noże do rzucania":          KronikiElevenaItemData("Weapon",        213700_341, ItemClassification.useful, 2),
    "Ostrze ognia":              KronikiElevenaItemData("Weapon",        213700_342, ItemClassification.useful, 2),
    "Pędzel Guerteny":           KronikiElevenaItemData("Weapon",        213700_343, ItemClassification.useful, 2),
    "Nóż malarski":              KronikiElevenaItemData("Weapon",        213700_344, ItemClassification.useful, 2),
    "Szabla":                    KronikiElevenaItemData("Weapon",        213700_345, ItemClassification.useful, 2),
    "Ostrze barbarzyńcy":        KronikiElevenaItemData("Weapon",        213700_346, ItemClassification.useful, 2),
    "Kosa śmierci":              KronikiElevenaItemData("Weapon",        213700_347, ItemClassification.useful, 2),
    "Rubinowa różdżka":          KronikiElevenaItemData("Weapon",        213700_348, ItemClassification.useful, 2),
    "Trójząb":                   KronikiElevenaItemData("Weapon",        213700_349, ItemClassification.useful, 2),
    "Berło śmierci":             KronikiElevenaItemData("Weapon",        213700_350, ItemClassification.useful, 2),
    "Rękawice kuchenne":         KronikiElevenaItemData("Weapon",        213700_351, ItemClassification.useful, 2),
    "Rękawice z brązu":          KronikiElevenaItemData("Weapon",        213700_352, ItemClassification.useful, 2),
    "Rękawice śmierci":          KronikiElevenaItemData("Weapon",        213700_353, ItemClassification.useful, 2),
    "Tasak":                     KronikiElevenaItemData("Weapon",        213700_354, ItemClassification.useful, 2),
    "Ostrze mrozu":              KronikiElevenaItemData("Weapon",        213700_355, ItemClassification.useful, 2),
    "Klinga śmierci":            KronikiElevenaItemData("Weapon",        213700_356, ItemClassification.useful, 2),
    # Dark Eleven
    "Miecz Dark Elevena":        KronikiElevenaItemData("Weapon",        213700_357, ItemClassification.useful, 1),
    "Ostrze Dark Elevena":       KronikiElevenaItemData("Weapon",        213700_358, ItemClassification.useful, 1),
    "Laska Dark Elevena":        KronikiElevenaItemData("Weapon",        213700_359, ItemClassification.useful, 1),
    "Kastet Dark Elevena":       KronikiElevenaItemData("Weapon",        213700_360, ItemClassification.useful, 1),

    # Variables & Switches
    # Temmie
    "Temmie 1":                     KronikiElevenaItemData("Quest",        213700_361, ItemClassification.progression, 1),
    "Temmie 2":                     KronikiElevenaItemData("Quest",        213700_362, ItemClassification.progression, 1),
    "Temmie 3":                     KronikiElevenaItemData("Quest",        213700_363, ItemClassification.progression, 1),
    "Temmie 4":                     KronikiElevenaItemData("Quest",        213700_364, ItemClassification.progression, 1),
    "Temmie 5":                     KronikiElevenaItemData("Quest",        213700_365, ItemClassification.progression, 1),
    "Temmie 6":                     KronikiElevenaItemData("Quest",        213700_366, ItemClassification.progression, 1),
    "Temmie 7":                     KronikiElevenaItemData("Quest",        213700_367, ItemClassification.progression, 1),
    "Temmie 8":                     KronikiElevenaItemData("Quest",        213700_368, ItemClassification.progression, 1),
    "Temmie 9":                     KronikiElevenaItemData("Quest",        213700_369, ItemClassification.progression, 1),
    "Temmie 10":                    KronikiElevenaItemData("Quest",        213700_370, ItemClassification.progression, 1),
    # Doors
    "FNaF Door(Zachód)":            KronikiElevenaItemData("Quest",        213700_371, ItemClassification.progression, 1),
    "Sklep Door(pierwsze miasto)":  KronikiElevenaItemData("Quest",        213700_372, ItemClassification.progression, 1),
    
    # Phone
    "Telefon":                      KronikiElevenaItemData("Quest",        213700_373, ItemClassification.progression_skip_balancing, 1),


    # More Fillers: 100$, 400$, 1000$, Insta Heals
}